name: Daily Commit Workflow

on:
  schedule:
    # Runs at 00:00 UTC every day (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Replace this step with your email in its name
      - name: 24f1002092@ds.study.iitm.ac.in
        run: |
          echo "Task by $(whoami) at $(date)" >> timestamp.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add timestamp.txt
          git commit -m "Daily automated commit by workflow"
          git push
