name: My Email Trigger Action

on: [push, workflow_dispatch]

jobs:
  email_step_job:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002092@ds.study.iitm.ac.in
        run: echo "This step contains the specified email address."
      - name: Another step
        run: echo "This is another step in the workflow."
